const PROJECT_VERSION = process.env.npm_package_version

const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SUPABASE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY

const OPENFOODFACTS_API_URL = process.env.OPENFOODFACTS_API_URL
const OPENBEAUTYFACTS_API_URL = process.env.OPENBEAUTYFACTS_API_URL
const OPENPETFOODFACTS_API_URL = process.env.OPENPETFOODFACTS_API_URL
const OPENPRODUCTSFACTS_API_URL = process.env.OPENPRODUCTSFACTS_API_URL

export {
  OPENBEAUTYFACTS_API_URL,
  OPENFOODFACTS_API_URL,
  OPENPETFOODFACTS_API_URL,
  OPENPRODUCTSFACTS_API_URL,
  PROJECT_VERSION,
  SUPABASE_ANON_KEY,
  SUPABASE_PUBLISHABLE_KEY,
  SUPABASE_URL,
}
