const DB_TABLE_HOUSEHOLDS = 'households'
const DB_TABLE_HOUSEHOLD_MEMBERS = 'household_members'
const DB_TABLE_ITEMS = 'items'
const DB_TABLE_ITEM_BARCODES = 'item_barcodes'
const DB_TABLE_HOUSEHOLD_INVENTORY = 'household_inventory'

const DB_FUNCTION_CREATE_HOUSEHOLD = 'create_household'
const DB_FUNCTION_PING_DATABASE = 'ping_database'
const DB_FUNCTION_FIND_ITEM_BY_BARCODE = 'find_item_by_barcode'
const DB_FUNCTION_CREATE_ITEM = 'create_item'
const DB_FUNCTION_ADD_ITEM_TO_HOUSEHOLD = 'add_item_to_household'
const DB_FUNCTION_ATTACH_BARCODE = 'attach_barcode'

export {
  DB_TABLE_HOUSEHOLDS,
  DB_TABLE_HOUSEHOLD_MEMBERS,
  DB_TABLE_ITEMS,
  DB_TABLE_ITEM_BARCODES,
  DB_TABLE_HOUSEHOLD_INVENTORY,
  DB_FUNCTION_CREATE_HOUSEHOLD,
  DB_FUNCTION_PING_DATABASE,
  DB_FUNCTION_FIND_ITEM_BY_BARCODE,
  DB_FUNCTION_CREATE_ITEM,
  DB_FUNCTION_ADD_ITEM_TO_HOUSEHOLD,
  DB_FUNCTION_ATTACH_BARCODE,
}
