import { createClient } from '@supabase/supabase-js'

// Generated by `opennextjs-cloudflare build`.
import { default as handler } from './.open-next/worker.js'
import { checkSupabaseHealth } from './src/lib/health/check-supabase-health'

interface WorkerEnv extends CloudflareEnv {
  NEXT_PUBLIC_SUPABASE_URL: string
  NEXT_PUBLIC_SUPABASE_ANON_KEY: string
}

export default {
  fetch: handler.fetch,

  async scheduled(_controller: ScheduledController, env: WorkerEnv) {
    try {
      const supabase = createClient(
        env.NEXT_PUBLIC_SUPABASE_URL,
        env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
      )
      const result = await checkSupabaseHealth(supabase)

      if (result.status === 'unhealthy') {
        console.error(
          `Supabase keep-alive health check failed: ${result.message}`,
        )
      }
    } catch (error: unknown) {
      console.error('Supabase keep-alive health check failed', error)
    }
  },
} satisfies ExportedHandler<WorkerEnv>
